#Template v2.0

name: Deploy to EC2

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]

  workflow_dispatch:


env:
  DATABASE_HOST: ${{secrets.SERVER_REMOTE}}
  DATABASE_NAME: ${{secrets.SERVER_DB_NAME}}
  DATABASE_USERNAME: ${{secrets.SERVER_DB_USERNAME}}
  DATABASE_PASSWORD:  ${{secrets.SERVER_DB_PASSWORD}}
  DATABASE_SCRIPT: 'script.sql'
 

jobs:
  Import_SQL:
    runs-on: ubuntu-latest
    name: MySQL Deploy to RDS
    if: ${{ false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import SQL Script
        run: |
              mysql --host=$DATABASE_HOST --user=$DATABASE_USERNAME --password=$DATABASE_PASSWORD --database $DATABASE_NAME < $DATABASE_SCRIPT
  
  Deploy_staging:
    name: Deploy Staging
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: http://18.216.147.167/index.php
    #needs: [Import_SQL]
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Clean EC2
        run: | 
              sudo rm -r /var/www/html/
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_STAGING }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_STAGING }}
          REMOTE_USER: ${{ secrets.USERNAME_STAGING }}
          TARGET: ${{ secrets.TARGET_DIR_STAGING }}

  Deploy_production:
    name: Deploy Production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: http://18.118.199.215/index.php
    needs: [Deploy_staging]
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_PRODUCTION }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_PRODUCTION }}
          REMOTE_USER: ${{ secrets.USERNAME_PRODUCTION }}
          TARGET: ${{ secrets.TARGET_DIR_PRODUCTION }}
